### ISSUE TITLE
compiles but GUI does not open

### ISSUE THREAD

**Issue by joeblew99** [andydotxyz/dicomgraphics#4]
using gomodules and latest golang on mac.

go run fails with:

```

mkdir -p /Users/apple/workspace/go/src/github.com/andydotxyz/dicomgraphics
cd /Users/apple/workspace/go/src/github.com/andydotxyz/dicomgraphics && cd .. && rm -rf dicomgraphics &&  git clone ssh://git@github.com/andydotxyz/dicomgraphics.git
Cloning into 'dicomgraphics'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 63 (delta 24), reused 52 (delta 17), pack-reused 0
Receiving objects: 100% (63/63), 371.44 KiB | 1.11 MiB/s, done.
Resolving deltas: 100% (24/24), done.
#cd /Users/apple/workspace/go/src/github.com/andydotxyz/dicomgraphics && git checkout master
cd /Users/apple/workspace/go/src/github.com/andydotxyz/dicomgraphics/cmd/dicomviewer && go run main.go
# fyne.io/fyne/internal/driver/gl
../../../../pkg/mod/fyne.io/fyne@v1.1.0/internal/driver/gl/gl_darwinfix.go:10:5: warning: 'NSOpenGLContext' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit. [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:202:12: note: 'NSOpenGLContext' has been explicitly marked deprecated here
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x41af3e7]

goroutine 20 [running]:
fyne.io/fyne/dialog.(*dialog).setButtons(0xc0002d0000, 0x43faf60, 0xc0002e4000)
        /Users/apple/workspace/go/pkg/mod/fyne.io/fyne@v1.1.0/dialog/base.go:79 +0x277
fyne.io/fyne/dialog.createTextDialog(0x438adbf, 0x12, 0x43aa1b2, 0x28, 0x43edde0, 0xc0000922c0, 0x0, 0x0, 0x0, 0x0)
        /Users/apple/workspace/go/pkg/mod/fyne.io/fyne@v1.1.0/dialog/information.go:17 +0x221
fyne.io/fyne/dialog.NewInformation(...)
        /Users/apple/workspace/go/pkg/mod/fyne.io/fyne@v1.1.0/dialog/information.go:26
main.showError.func1(0x43aa1b2, 0x28)
        /Users/apple/workspace/go/src/github.com/andydotxyz/dicomgraphics/cmd/dicomviewer/main.go:198 +0x6c
created by main.showError
        /Users/apple/workspace/go/src/github.com/andydotxyz/dicomgraphics/cmd/dicomviewer/main.go:197 +0x49
exit status 2
make: *** [go-sample-run] Error 1

```

**Comment by andydotxyz** [comment]
Quite right, Fyne changed how dialogs work - I have a short term fix incoming
